import os
import json
from google import genai
from google.genai import types

def main():
    app_map_file = "app_map.json"
    if not os.path.exists(app_map_file):
        print(f"File {app_map_file} not found in the current directory.")
        return

    with open(app_map_file, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
            
            # Immediately strip old keys
            data.pop("Features_Tested", None)
            data.pop("Screens_Visited", None)
            
            memory_text = json.dumps(data)
        except json.JSONDecodeError:
            print("Failed to parse app_map.json")
            return
            
    print(f"Current app_map.json size: {len(memory_text)} characters")
    print("Sending to LLM for semantic deduplication and compaction...")

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY environment variable not set.")
        return
        
    client = genai.Client(api_key=api_key)
    
    prompt = f"""
You are an expert QA testing coordinator. The following JSON is an "App Map" generated by an automated testing agent. Over time, the agent has logged the same bugs and features multiple times using slightly different wording (e.g. "Onboarding Flow Interruptibility" vs "Onboarding Flow Interruption", or logging the same UI state bug 9 times).

Your job is to semantically deduplicate and compact this JSON.

1. Under each Screen in `Screens`, merge any conceptually identical items in `Features_Tested` into a single, clean entry. Keep the `Status` ("PASS" or "FAIL").
2. Under `Known_Bugs`, merge any conceptually identical bugs into a single entry. Keep the most descriptive wording. Ensure all duplicate instances (like the 9 copies of the `clickable: false` bug) are reduced to 1.
3. Output the exact same schema, just smaller and deduplicated.

Current App Map:
{memory_text}

Output ONLY valid JSON.
"""

    model_name = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
    try:
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.0
            )
        )

        text_response = response.text.strip()
        if text_response.startswith("```json"):
            text_response = text_response[7:]
        elif text_response.startswith("```"):
            text_response = text_response[3:]
        if text_response.endswith("```"):
            text_response = text_response[:-3]
            
        text_response = text_response.strip()
        
        app_map = json.loads(text_response)
        
        # Verify schema is mostly intact before overwriting
        if "Metadata" in app_map and "Screens" in app_map and "Known_Bugs" in app_map:
            with open(app_map_file, "w", encoding="utf-8") as f:
                json.dump(app_map, f, indent=2)
            print("Successfully compacted app_map.json!")
            print(f"New size: {len(text_response)} characters")
        else:
            print("LLM returned an invalid schema. Compaction aborted.")
            
    except Exception as e:
        print(f"An error occurred during compaction: {str(e)}")

if __name__ == "__main__":
    main()
